import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const nunito = Nunito({ subsets: ["latin"], variable: '--font-nunito' });

export const metadata: Metadata = {
  title: "Bucket Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`h-screen max-h-screen max-w-screen w-screen`,nunito.variable )}>{children}</body>
    </html>
  );
}
